---
  swagger: "2.0"
  info:
    title: "OmegaTrace Reporting"
    description: "OmegaTrace Reporting Platform."
    version: "1.0"
  consumes:
    - application/json
  produces:
    - application/json